languages:
  JavaScript: true
engines:
  duplication:
    enabled: true
    # need this: Config Error: Unable to run the duplication engine without any languages enabled.
    config:
      languages:
      - javascript
    exclude_paths:
    - "test/"
exclude_paths:
- "lib/"
